const items = [
    {id:1, prodCategory:"T-shirt", mainImage:'img/products/f1.jpg', prodName:"Cartoon colored T-Shirt", rating:`5/5`, p:150, prodPrice:150, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:2, prodCategory:"T-shirt", mainImage:'img/products/f2.jpg', prodName:"Cartoon lily T-Shirt", rating:`5/5`, prodPrice:150, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:3, prodCategory:"T-shirt", mainImage:'img/products/f3.jpg', prodName:"Cartoon brown T-Shirt", rating:`5/5`, prodPrice:150, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:4, prodCategory:"T-shirt", mainImage:'img/products/f4.jpg', prodName:"Cartoon White T-Shirt", rating:`5/5`, prodPrice:150, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:5, prodCategory:"T-shirt",  mainImage:'img/products/f5.jpg', prodName:"Cartoon Purple T-Shirt", rating:`5/5`, prodPrice:150, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:6, prodCategory:"T-shirt",  mainImage:'img/products/f6.jpg', prodName:"Cartoon Red-Blue T-Shirt", rating:`5/5`, prodPrice:150, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:7, prodCategory:"T-shirt",  mainImage:'img/products/f7.jpg', prodName:"Cartoon Girls Leggy", rating:`5/5`, prodPrice:250, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:8, prodCategory:"T-shirt",  mainImage:'img/products/f8.jpg', prodName:"Cartoon Girls Top", rating:`5/5`, prodPrice:175, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:9, prodCategory:"shirt",  mainImage:'img/products/n1.jpg', prodName:"Light Blue Shirt", rating:`5/5`, prodPrice:300, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:10, prodCategory:"shirt",  mainImage:'img/products/n2.jpg', prodName:"Lined Gray Shirt", rating:`5/5`, prodPrice:300, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:11, prodCategory:"shirt",  mainImage:'img/products/n3.jpg', prodName:"White Plan Shirt", rating:`5/5`, prodPrice:300, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:12, prodCategory:"shirt",  mainImage:'img/products/n4.jpg', prodName:"Half-slives designed Shirt", rating:`5/5`, prodPrice:300, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:13, prodCategory:"shirt",  mainImage:'img/products/n5.jpg', prodName:"Denim blue Shirt", rating:`5/5`, prodPrice:450, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:14, prodCategory:"shirt",  mainImage:'img/products/n6.jpg', prodName:"Short pant", rating:`5/5`, prodPrice:100, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:15, prodCategory:"shirt",  mainImage:'img/products/n7.jpg', prodName:"Dark Yellow Plan Shirt", rating:`5/5`, prodPrice:250, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"},
    {id:16, prodCategory:"shirt",  mainImage:'img/products/n8.jpg', prodName:"Dark Gray Plan Shirt", rating:`5/5`, prodPrice:230, description:"The Gildan Ultra Cotton T-shirt is made from a substantial 6.0 oz. per.sq.yd. fabric constructed from 100% cotton, this classic fit preshrunk jersey knit provides unmatched comfort with each wear. Featuring a taped neck and shoulder, and a seamless double needle collar, and available in a range of colors, it offers it all in the ultimate head-turning package"}      
];

localStorage.setItem('listItem', JSON.stringify(items));
